name: Build, Scan, and Push FastAPI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Free up space before building
      - name: Clean up disk space
        run: |
          echo "Cleaning up disk space..."
          docker system prune -af || true
          sudo rm -rf /tmp/* || true
          df -h

      # Login to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest -f ./Day3_Workshop/Dockerfile ./Day3_Workshop

      # Scan Docker image with Trivy
      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
         scan-type: 'fs'
         scan-ref: './Day3_Workshop'
         format: 'table' 
         severity: 'HIGH,CRITICAL'
         ignore-unfixed: true
         vuln-type: 'os,library'
         exit-code: 0
         output: 'trivy-report.txt'
         args: '--skip-db-update --skip-version-check'
          

      # Upload Trivy report as an artifact
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt

      # Push image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
