name: Trivy Image Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug - list files to confirm structure
      - name: Debug — list all files
        run: |
          echo "Current directory: $(pwd)"
          ls -R

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build your Docker image
      - name: Build Docker image
        run: |
          docker build -t myapp:latest -f ./Day3Workshop/Day3_Workshop/dockerfile ./Day3Workshop/Day3_Workshop

      # Step 5: Run Trivy image scan
      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'fastapi-app:latest'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: 0
          vuln-type: 'os,library'
          output: 'trivy-report.txt'

      # Step 6: Upload Trivy scan results
      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-report
          path: trivy-report.txt
